In [4]:
# 1) punkt wyjscia: stworzyc (za pomoca interfejsu Sequential) siec gesta z 1 wastwa ukryta
# sprawdzic accuracy na testowym
# policz recznie ile jest paremetrow w tej sieci

# 2) przepisac te sama siec uzywajac interfejsu "funkcyjnego" keras
# inputs = keras.Input(shape = (,...),etc.)
# 1hidden = keras.Dense(...)(inputs)
# 2hidden = keras.Dense(...)(1hidden)
# output = 
# model = keras.Model(inputs = ..., ouyuts = ...)

# 3) wywolanie zwrotne (callbacks)
# keras callbacks ...
# 3 - 1 keras.callbacks.EarlyStopping(...)
# 3 - 2 keras.ModelCheckpoint(...) (tutaj zaladowac go potem i porownac z przetrenowanym)
# 3 - 3 keras.TensorBoard(...nazwa pliku logowania...)
# %load_ext tensorboard
# tensorboard --logdir sciezkaDoPlikuLogowania

# 4) stworzyc mala siec konwolucyjna dla zadania MNIST
# 2x (layers.Conv2D ( 32 i 64, kernel 3x3)  + MaxPooling2D)
# layers.Conv2D (128)
# layers.Flatten
# warstwa Dense (odpowiedni rozmiar)

# psy i koty na colabie, 6 warstw 

In [5]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import plotly.express as px
from tensorflow import keras
from tensorflow.keras.datasets import mnist
from tensorflow.keras import layers

In [6]:
# Wczytywanie zbioru 

(train_images, train_labels), (test_images, test_labels)= mnist.load_data()

In [7]:
train_images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [8]:
train_labels[0]

5

In [9]:
np.unique(train_labels)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [10]:
train_images.shape, train_labels.shape, test_images.shape, test_labels

((60000, 28, 28),
 (60000,),
 (10000, 28, 28),
 array([7, 2, 1, ..., 4, 5, 6], dtype=uint8))

In [11]:
train_flat = train_images.reshape((60000, 28*28))

test_flat = test_images.reshape((10000, 28*28))

train = train_flat.astype("float32") / 255
test = test_flat.astype("float32") / 255
train[0].shape

(784,)

In [12]:
model = keras.Sequential([
    layers.Dense(512, activation = 'relu'),
    layers.Dense(10, activation = 'softmax')
])

model.compile(optimizer = 'rmsprop', loss = 'sparse_categorical_crossentropy', metrics = ["accuracy"])
model.fit(train, train_labels, epochs = 3)

Epoch 1/3
1875/1875 [==============================] - 8s 4ms/step - loss: 0.2016 - accuracy: 0.9407
Epoch 2/3
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0906 - accuracy: 0.9739
Epoch 3/3
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0665 - accuracy: 0.9811


In [13]:
model.evaluate(test, test_labels)

313/313 [==============================] - 1s 2ms/step - loss: 0.1030 - accuracy: 0.9740


[0.10299500823020935, 0.9739999771118164]

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               401920    
                                                                 
 dense_1 (Dense)             (None, 10)                5130      
                                                                 
Total params: 407,050
Trainable params: 407,050
Non-trainable params: 0
_________________________________________________________________


In [15]:
# 2) przepisac te sama siec uzywajac interfejsu "funkcyjnego" keras
# inputs = keras.Input(shape = (,...),etc.)
# 1hidden = keras.Dense(...)(inputs)
# 2hidden = keras.Dense(...)(1hidden)
# output = 
# model = keras.Model(inputs = ..., ouyuts = ...)

In [16]:
train.shape[1]

784

In [17]:
inputs = keras.Input(shape=(train.shape[1],))
hidden1 = keras.layers.Dense(256, activation = 'relu')(inputs)
hidden2 = keras.layers.Dense(256, activation = 'relu')(hidden1)
output = keras.layers.Dense(10, activation = 'softmax')(hidden2)
model = keras.Model(inputs=inputs, outputs=output)

model.compile(optimizer = 'rmsprop', loss = 'sparse_categorical_crossentropy', metrics = ["accuracy"])
model.fit(train, train_labels, epochs = 3)

Epoch 1/3
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2006 - accuracy: 0.9400
Epoch 2/3
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0937 - accuracy: 0.9735
Epoch 3/3
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0725 - accuracy: 0.9802


In [18]:
28*28*512+512+512*10+10

407050

In [19]:
model.evaluate(test, test_labels)

313/313 [==============================] - 1s 2ms/step - loss: 0.1071 - accuracy: 0.9748


[0.10706107318401337, 0.9747999906539917]

In [20]:
# 4) stworzyc mala siec konwolucyjna dla zadania MNIST
# 2x (layers.Conv2D ( 32 i 64, kernel 3x3)  + MaxPooling2D)
# layers.Conv2D (128)
# layers.Flatten
# warstwa Dense (odpowiedni rozmiar)

In [26]:
inputs = keras.Input(shape=(28,28,1))
l = layers.Conv2D(filters = 32, kernel_size=3, activation='relu')(inputs)
l = layers.MaxPooling2D(pool_size=2)(l)
l = layers.Conv2D(128, kernel_size=5, activation = 'relu')(l)
l = layers.Flatten()(l)
outputs = layers.Dense(10, activation = 'softmax')(l)
modelconv = keras.Model(inputs=inputs, outputs=outputs)
modelconv.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_5 (InputLayer)        [(None, 28, 28, 1)]       0         
                                                                 
 conv2d_4 (Conv2D)           (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 13, 13, 32)       0         
 2D)                                                             
                                                                 
 conv2d_5 (Conv2D)           (None, 9, 9, 128)         102528    
                                                                 
 flatten_2 (Flatten)         (None, 10368)             0         
                                                                 
 dense_6 (Dense)             (None, 10)                103690    
                                                           

In [27]:
modelconv.compile(optimizer = 'rmsprop', loss = 'sparse_categorical_crossentropy', metrics = ["accuracy"])
modelconv.fit(train_images, train_labels, epochs = 3)

Epoch 1/3
1875/1875 [==============================] - 92s 48ms/step - loss: 0.3980 - accuracy: 0.9589
Epoch 2/3
1875/1875 [==============================] - 93s 49ms/step - loss: 0.0614 - accuracy: 0.9840
Epoch 3/3
1875/1875 [==============================] - 96s 51ms/step - loss: 0.0534 - accuracy: 0.9870


In [28]:
modelconv.evaluate(test_images,test_labels)

313/313 [==============================] - 12s 39ms/step - loss: 0.0757 - accuracy: 0.9802


[0.0756700411438942, 0.9801999926567078]

In [47]:
inputs = keras.Input(shape=(28, 28, 1))
l = layers.Conv2D(filters=6, kernel_size=5, strides=1, activation='relu')(inputs)
l = layers.AveragePooling2D(pool_size=2, strides=2)(l)
l = layers.Conv2D(filters=16, kernel_size=5, strides=1, activation='relu')(l)
l = layers.AveragePooling2D(pool_size=2, strides=2)(l)
l = layers.Dense(120, activation = 'relu')(l)
l = layers.Flatten()(l)
l = layers.Dense(84, activation = 'relu')(l)
outputs = layers.Dense(10, activation = 'softmax')(l)
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 784)]             0         
                                                                 
 dense_2 (Dense)             (None, 256)               200960    
                                                                 
 dense_3 (Dense)             (None, 256)               65792     
                                                                 
 dense_4 (Dense)             (None, 10)                2570      
                                                                 
Total params: 269,322
Trainable params: 269,322
Non-trainable params: 0
_________________________________________________________________


In [48]:
modelconv.compile(optimizer = 'rmsprop', loss = 'sparse_categorical_crossentropy', metrics = ["accuracy"])
modelconv.fit(train_images, train_labels, epochs = 3)

Epoch 1/3
1875/1875 [==============================] - 91s 48ms/step - loss: 0.0544 - accuracy: 0.9885
Epoch 2/3
1875/1875 [==============================] - 97s 52ms/step - loss: 0.0413 - accuracy: 0.9910
Epoch 3/3
1875/1875 [==============================] - 98s 52ms/step - loss: 0.0409 - accuracy: 0.9917


In [50]:
modelconv.evaluate(test_images, test_labels)

313/313 [==============================] - 12s 39ms/step - loss: 0.0884 - accuracy: 0.9863


[0.08839602768421173, 0.986299991607666]

In [53]:
inputs = keras.Input(shape=(28, 28, 1))
l = layers.Conv2D(filters=6, kernel_size=5, strides=1, activation='relu')(inputs)
l = layers.MaxPooling2D(pool_size=2, strides=2)(l)
l = layers.Conv2D(filters=16, kernel_size=5, strides=1, activation='relu')(l)
l = layers.MaxPooling2D(pool_size=2, strides=2)(l)
l = layers.Dense(120, activation = 'relu')(l)
l = layers.Flatten()(l)
l = layers.Dense(84, activation = 'relu')(l)
outputs = layers.Dense(10, activation = 'softmax')(l)
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 784)]             0         
                                                                 
 dense_2 (Dense)             (None, 256)               200960    
                                                                 
 dense_3 (Dense)             (None, 256)               65792     
                                                                 
 dense_4 (Dense)             (None, 10)                2570      
                                                                 
Total params: 269,322
Trainable params: 269,322
Non-trainable params: 0
_________________________________________________________________


In [54]:
modelconv.compile(optimizer = 'rmsprop', loss = 'sparse_categorical_crossentropy', metrics = ["accuracy"])
modelconv.fit(train_images, train_labels, epochs = 3)

Epoch 1/3
1875/1875 [==============================] - 76s 40ms/step - loss: 0.0459 - accuracy: 0.9922
Epoch 2/3
1875/1875 [==============================] - 75s 40ms/step - loss: 0.0388 - accuracy: 0.9938
Epoch 3/3
1875/1875 [==============================] - 75s 40ms/step - loss: 0.0378 - accuracy: 0.9948


In [55]:
modelconv.evaluate(test_images, test_labels)

313/313 [==============================] - 10s 33ms/step - loss: 0.1654 - accuracy: 0.9859


[0.1654285192489624, 0.9858999848365784]